version: "3.9"
services:

  database:
    container_name: psqldb
    expose: 5432
    image: valenciaga/hilogame:database
    volumes:
        - pgdata:/var/lib/postgresql/data

  app:
    container_name: hilogame
    image: valenciaga/hilogame:game
    env_file: .env
    depends_on:
        - database
    ports:
        - 1337:1337
    volumes:
        - ./.env:/app/.env:ro

volumes:
  pgdata:
