version: "3.9"
services:

  database:
    container_name: hilogamedb
    env_file: db.env
    expose: 
        - 5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    image: hilogamedb:latest
    user: postgres
    volumes:
        - pgdata:/postgresql/data

  app:
    container_name: hilogameapi
    image: hilogameapi:latest
    env_file: .env
    depends_on:
      database:
        condition: service_healthy
    ports:
        - 1337:1337
    volumes:
        - ./.env:/app/.env:ro

volumes:
  pgdata:
