version: "3.9"
services:

  database:
    container_name: psqldb
    build: 
      context: ./psqldb
    ports: 
        - 5432:5432
    volumes:
        - pgdata:/var/lib/postgresql/data

  app:
    container_name: hilogame
    build: .
    depends_on:
        - database
    links:
        - database

volumes:
  pgdata:
