version: "3.9"
services:

  database:
    container_name: psqldb
    build: 
      context: ./psqldb
    volumes:
        - pgdata:/var/lib/postgresql/data

  app:
    container_name: hilogame
    build: .
    depends_on:
        - database
    environment:
        - PYTHONUNBUFFERED=1
    links:
        - database
    ports:
        - 1337:1337
    stdin_open: true
    tty: true
    volumes:
      - type: bind
        source: ./.env
        target: /app/.env
        read_only: true

volumes:
  pgdata:
