---
- hosts: all
  become: true
  vars:
    created_username: alex

  tasks:
    - name: Update repo
      ansible.builtin.apt:
        update_cache: yes

    - name: Install required system packages
      ansible.builtin.apt:
        pkg:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - virtualenv
        state: latest

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable
        state: present

    - name: Install docker-ce
      apt:
        name: docker-ce
        state: latest
        update_cache: true

    - name: Install containerd
      apt:
        name: containerd.io
        state: latest

    - name: Install docker-compose-plugin
      apt:
        name: docker-compose
        state: latest

    - name: Install Docker Module for Python
      pip:
        name: docker

    - name: Enable Docker service
      ansible.builtin.command: systemctl enable docker

    - name: Start Docker service
      ansible.builtin.command: systemctl start docker

    - name: Log into DockerHub
      docker_login:
        username: "{{ dockerhub_username }}"
        password: "{{ dockerhub_password }}"

    - name: Create .env file
      ansible.builtin.copy:
        dest: .env
        content: |
          DB_USER="{{ db_username }}"
          DB_PASSWORD="{{ db_password }}"
          DB_HOST="{{ db_host }}"
          DB_PORT="{{ db_port }}"
          DB_NAME="{{ db_name }}"

    - name: Create docker-compose file
      ansible.builtin.copy:
        dest: docker-compose.yml
        content: |
          version: "3"
          services:

            database:
              container_name: psqldb
              ports:
                  - 5432:5432
              image: valenciaga/hilogame:database
              volumes:
                  - pgdata:/var/lib/postgresql/data

            app:
              container_name: hilogame
              image: valenciaga/hilogame:game
              depends_on:
                  - database
              ports:
                  - 1337:1337
              volumes:
                  - ./.env:/app/.env:ro

          volumes:
            pgdata:
    
    - name: Run docker compose up
      ansible.builtin.command: docker-compose up -d
