import pytest

from hilo.models.card import Card, Ranks, Suits


@pytest.fixture
def seeded_deck():
    return [
        Card.create(Ranks.J, Suits.S),
        Card.create(Ranks.TEN, Suits.D),
        Card.create(Ranks.Q, Suits.H),
        Card.create(Ranks.TEN, Suits.C),
        Card.create(Ranks.THREE, Suits.D),
        Card.create(Ranks.K, Suits.H),
        Card.create(Ranks.SEVEN, Suits.C),
        Card.create(Ranks.Q, Suits.D),
        Card.create(Ranks.TEN, Suits.H),
        Card.create(Ranks.SIX, Suits.D),
        Card.create(Ranks.FOUR, Suits.H),
        Card.create(Ranks.K, Suits.S),
        Card.create(Ranks.FIVE, Suits.S),
        Card.create(Ranks.THREE, Suits.C),
        Card.create(Ranks.J, Suits.C),
        Card.create(Ranks.EIGHT, Suits.S),
        Card.create(Ranks.NINE, Suits.S),
        Card.create(Ranks.NINE, Suits.C),
        Card.create(Ranks.TWO, Suits.S),
        Card.create(Ranks.A, Suits.S),
        Card.create(Ranks.K, Suits.D),
        Card.create(Ranks.Q, Suits.S),
        Card.create(Ranks.SEVEN, Suits.H),
        Card.create(Ranks.EIGHT, Suits.C),
        Card.create(Ranks.K, Suits.C),
        Card.create(Ranks.A, Suits.H),
        Card.create(Ranks.NINE, Suits.H),
        Card.create(Ranks.J, Suits.D),
        Card.create(Ranks.EIGHT, Suits.H),
        Card.create(Ranks.FOUR, Suits.D),
        Card.create(Ranks.SIX, Suits.C),
        Card.create(Ranks.TWO, Suits.C),
        Card.create(Ranks.FIVE, Suits.C),
        Card.create(Ranks.SIX, Suits.S),
        Card.create(Ranks.A, Suits.D),
        Card.create(Ranks.TWO, Suits.H),
        Card.create(Ranks.FOUR, Suits.S),
        Card.create(Ranks.TWO, Suits.D),
        Card.create(Ranks.SEVEN, Suits.S),
        Card.create(Ranks.SEVEN, Suits.D),
        Card.create(Ranks.A, Suits.C),
        Card.create(Ranks.Q, Suits.C),
        Card.create(Ranks.THREE, Suits.S),
        Card.create(Ranks.FIVE, Suits.H),
        Card.create(Ranks.THREE, Suits.H),
        Card.create(Ranks.SIX, Suits.H),
        Card.create(Ranks.EIGHT, Suits.D),
        Card.create(Ranks.FOUR, Suits.C),
        Card.create(Ranks.FIVE, Suits.D),
        Card.create(Ranks.TEN, Suits.S),
        Card.create(Ranks.J, Suits.H),
        Card.create(Ranks.NINE, Suits.D),
    ]
