name: Terraform apply

on:
  push:
    pull_request:
      branches:
        - 'master'

env:
  TF_LOG: INFO
  TF_INPUT: false


jobs:

  terraform-apply:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./terraform

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: '1.3.7'
      
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Terraform Init
        id: init
        working-directory: ./terraform
        run: terraform init
