name: Terraform plan

on:
  push:
    pull_request:
      branches:
        - '*'
        - '!master'

env:
  TF_LOG: INFO
  TF_INPUT: false


jobs:

  terraform-plan:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./terraform

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: '1.3.7'
      
      - name: Terraform Init
        id: init
        working-directory: ./terraform
        run: terraform init

      - name: Terraform Validate
        id: validate
        if: success() || failure()
        run: terraform validate -no-color

      - name: Terraform Plan
        id: plan
        working-directory: ./terraform
        run: terraform plan -no-color -var "pvt_key=${{ secrets.SSH_PVT_KEY }}" -var "do_token=${{ secrets.DO_PAT }}" -out=tfplan
      
      - name: Save Artifact
        id: save-artifact
        uses: actions/upload-artifact@v3
        with:
          name: tfplan
          path: ./terraform/tfplan
       
      - name: Comment Plan
        id: comment-plan
        uses: peter-evans/create-or-update-comment@v3
        with:
          token: ${{ secrets.GH_PAT }}
          issue-number: ${{ github.event.pull_request.number }} 
          body: |
            Terraform Plan:

            ```
            ${{ steps.plan.outputs.plan }}
            ```

            Plan saved to GH artifacts.
