name: Terraform apply

on:
  pull_request:
    types: 
        - edited
    branches:
        - 'master-test'

permissions: write-all

env:
  TF_LOG: INFO
  TF_INPUT: false


jobs:

  terraform-apply:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./terraform

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: '1.3.7'
      
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DO_PAT }}

      - name: Terraform Init
        id: init
        working-directory: ./terraform
        run: terraform init

      - name: Terraform Plan
        id: plan
        working-directory: ./terraform
        run: terraform plan -no-color -var "pvt_key=${{ secrets.SSH_PVT_KEY }}" -var "do_token=${{ secrets.DO_PAT }}" -out=tfplan

      - name: Terraform apply
        id: apply
        working-directory: ./terraform
        env:
          dockerhub_username: ${{ secrets.DH_LOGIN_USERNAME }}
          dockerhub_password: ${{ secrets.DH_LOGIN_PASSWORD }}
        run: |
          terraform apply -input=false -no-color tfplan

      
      - name: Add Apply Comment
        id: comment-apply
        uses: actions/github-script@v7
        env:
          PLAN: "terraform\n${{ steps.apply.outputs.apply }}"
        with:
          github-token: ${{ secrets.GH_PAT }}
          script: |
            const output = `### Terraform Apply `${{ steps.apply.outcome }}\`
            Show Apply
          
            \`\`\`${process.env.PLAN}\`\`\`
          
          
          
            *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`, Workflow: \`${{ github.workflow }}\`*`;
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })
